/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userui;

import javax.swing.JOptionPane;
import ui.LoginFrame;
import utility.CommonOperations;

/**
 *
 * @author ADITYA
 */
public class UserMainScreen extends javax.swing.JFrame {

    private String username;

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public UserMainScreen() {
        initComponents();
        setSize(1000, 650);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        myDesktopPane1 = new userui.MyDesktopPane();
        myDesktopPane2 = new userui.MyDesktopPane();
        myDesktopPane3 = new userui.MyDesktopPane();
        myDesktopPane4 = new userui.MyDesktopPane();
        myDesktopPane5 = new userui.MyDesktopPane();
        myDesktopPane6 = new userui.MyDesktopPane();
        myDesktopPane7 = new userui.MyDesktopPane();
        myDesktopPane8 = new userui.MyDesktopPane();
        myDesktopPane9 = new userui.MyDesktopPane();
        myDesktopPane10 = new userui.MyDesktopPane();
        myDesktopPane11 = new userui.MyDesktopPane();
        myDesktopPane12 = new userui.MyDesktopPane();
        myDesktopPane13 = new userui.MyDesktopPane();
        myDesktopPane14 = new userui.MyDesktopPane();
        myDesktopPane15 = new userui.MyDesktopPane();
        myDesktopPane16 = new userui.MyDesktopPane();
        myDesktopPane17 = new userui.MyDesktopPane();
        myDesktopPane18 = new userui.MyDesktopPane();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        deskpane = new userui.MyDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jmiChangePassword = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jmiLogout = new javax.swing.JMenuItem();
        jmExit = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane1.setLayer(deskpane, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(deskpane, javax.swing.GroupLayout.DEFAULT_SIZE, 633, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(deskpane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
        );

        getContentPane().add(jDesktopPane1, java.awt.BorderLayout.CENTER);

        jMenu3.setText("Settings  ");

        jmiChangePassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userui/password.png"))); // NOI18N
        jmiChangePassword.setText("Change Password");
        jmiChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiChangePasswordActionPerformed(evt);
            }
        });
        jMenu3.add(jmiChangePassword);

        jMenuBar1.add(jMenu3);

        jMenu1.setText("Profile  ");

        jmiLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userui/logout.png"))); // NOI18N
        jmiLogout.setText("Log Out");
        jmiLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiLogoutActionPerformed(evt);
            }
        });
        jMenu1.add(jmiLogout);

        jMenuBar1.add(jMenu1);

        jmExit.setText("   Exit");
        jmExit.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jmExitMenuSelected(evt);
            }
        });
        jMenuBar1.add(jmExit);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiChangePasswordActionPerformed
        CommonOperations.showScreen(deskpane, new ChangePassword(username));
    }//GEN-LAST:event_jmiChangePasswordActionPerformed

    private void jmiLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiLogoutActionPerformed
        int result = JOptionPane.showConfirmDialog(this, "Are you sure you want to logout?", "Message from system", JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.YES_OPTION) {
            // System.exit(0);
            LoginFrame frame = new LoginFrame();
            frame.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_jmiLogoutActionPerformed

    private void jmExitMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jmExitMenuSelected
        int result = JOptionPane.showConfirmDialog(this, "Are you sure you want to exit?", "Message from system", JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jmExitMenuSelected

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserMainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserMainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserMainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserMainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserMainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private userui.MyDesktopPane deskpane;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jmExit;
    private javax.swing.JMenuItem jmiChangePassword;
    private javax.swing.JMenuItem jmiLogout;
    private userui.MyDesktopPane myDesktopPane1;
    private userui.MyDesktopPane myDesktopPane10;
    private userui.MyDesktopPane myDesktopPane11;
    private userui.MyDesktopPane myDesktopPane12;
    private userui.MyDesktopPane myDesktopPane13;
    private userui.MyDesktopPane myDesktopPane14;
    private userui.MyDesktopPane myDesktopPane15;
    private userui.MyDesktopPane myDesktopPane16;
    private userui.MyDesktopPane myDesktopPane17;
    private userui.MyDesktopPane myDesktopPane18;
    private userui.MyDesktopPane myDesktopPane2;
    private userui.MyDesktopPane myDesktopPane3;
    private userui.MyDesktopPane myDesktopPane4;
    private userui.MyDesktopPane myDesktopPane5;
    private userui.MyDesktopPane myDesktopPane6;
    private userui.MyDesktopPane myDesktopPane7;
    private userui.MyDesktopPane myDesktopPane8;
    private userui.MyDesktopPane myDesktopPane9;
    // End of variables declaration//GEN-END:variables
}
