/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adminui;

import javax.swing.JOptionPane;
import model.dao.CategoryInfoDAO;
import model.to.CategoryInfo;
import operations.Validations;
import sound.ProSound;
import utility.CommonOperations;

/**
 *
 * @author ADITYA
 */
public class AddNewCategory extends javax.swing.JInternalFrame {

    public AddNewCategory() {
        initComponents();
    }

    public AddNewCategory(CategoryInfo record) {
        this();
        if (record != null) {
            setTitle("Update Category Details");
            btnAdd.setText("Update Category Details");
            jtfCategoryID.setText(record.getCategoryid());
            jtfCategoryName.setText(record.getCategoryname());
            jtfCategoryID.setEditable(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtfCategoryID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtfCategoryName = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Add Category Details");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Enter Category ID:");

        jtfCategoryID.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jtfCategoryID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfCategoryIDKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Enter Category Name:");

        jtfCategoryName.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jtfCategoryName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfCategoryNameKeyTyped(evt);
            }
        });

        btnAdd.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnAdd.setText("Add Category Details");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminui/catiegoryid.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jtfCategoryID, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfCategoryName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfCategoryID, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56)
                        .addComponent(jtfCategoryName, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfCategoryNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCategoryNameKeyTyped
        if (!Character.isLetter(evt.getKeyChar())) {
            if (!Character.isWhitespace(evt.getKeyChar())) {
                evt.consume();
            }
        }
    }//GEN-LAST:event_jtfCategoryNameKeyTyped

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        ProSound ps = new ProSound();
        String message = "";
        boolean allvalid = true;
        String categoryid = jtfCategoryID.getText().trim();
        String categoryname = jtfCategoryName.getText().trim();
        if (Validations.isEmpty(categoryid)) {
            allvalid = false;
            message += "Please enter some value in Category ID box\n\n";
        }
        if (Validations.isEmpty(categoryname)) {
            allvalid = false;
            message += "Please enter some value in Category Name box\n\n";
        } else if (!Validations.onlyCharacter(categoryname)) {
            allvalid = false;
            message += "Please enter character value in Category Name box";
        }
        if (allvalid) {
            CategoryInfo record = new CategoryInfo();
            record.setCategoryid(categoryid);
            record.setCategoryname(categoryname);
            CategoryInfoDAO action = new CategoryInfoDAO();
            if (btnAdd.getText().contains("Add")) {
                if (action.insertRecord(record)) {
                    ps.button();
                    message = "Category information is added in the system";
                } else {
                    ps.computererror();
                    if (action.getErrormessage().contains("Duplicate entry") && action.getErrormessage().contains("key 1")) {
                        message = "CategoryID is a primary key and this category id already exists.\nPlease enter some other unique value in CategoryID";
                    } else if (action.getErrormessage().contains("Duplicate entry") && action.getErrormessage().contains("key 2")) {
                        message = "Category Name is a unique key and this category name already exists.\nPlease enter some other unique name in Category Name";
                    } else {
                        message = "Insertion Failure due to:" + action.getErrormessage();
                    }
                }
            } else if (btnAdd.getText().contains("Update")) {
                if (action.updateRecord(record)) {
                    ps.button();
                    message = "Category information is updated in the system";
                    CommonOperations.showScreen(getDesktopPane(), new ViewCategory());
                    dispose();
                } else {
                    ps.computererror();
                    if (action.getErrormessage().contains("Duplicate entry") && action.getErrormessage().contains("key 2")) {
                        message = "Category Name is a unique key and this category name already exists.\nPlease enter some other unique name in Category Name";
                    } else {
                        message = "Updation Failure due to:" + action.getErrormessage();
                        CommonOperations.showScreen(getDesktopPane(), new ViewCategory());
                        dispose();
                    }
                }
            } else {
                ps.computererror();
                message = "Not proper operation";
            }
        } else {
            ps.computererror();
        }
        JOptionPane.showMessageDialog(this, message);
    }//GEN-LAST:event_btnAddActionPerformed

    private void jtfCategoryIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCategoryIDKeyTyped
        if (!Character.isLetterOrDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_jtfCategoryIDKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jtfCategoryID;
    private javax.swing.JTextField jtfCategoryName;
    // End of variables declaration//GEN-END:variables
}
