/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adminui;

import javax.swing.JOptionPane;
import model.dao.TruckInfoDAO;
import model.to.TruckInfo;
import operations.Validations;
import sound.ProSound;
import utility.CommonOperations;

/**
 *
 * @author ADITYA
 */
public class AddTruckInfo extends javax.swing.JInternalFrame {

    /**
     * Creates new form AddTruckInfo
     */
    public AddTruckInfo() {
        initComponents();
    }

    public AddTruckInfo(TruckInfo record) {
        this();
        if (record != null) {
            setTitle("Update Truck Details");
            btnAdd.setText("Update Truck Details");
            jtfTruckNo.setText(record.getTruckno());
            jtfChassisNo.setText(record.getChassisno());
            jtfCapacity.setText(String.valueOf(record.getCapacity()));
            jtfWeight.setText(String.valueOf(record.getWeight()));
            jtfTruckNo.setEditable(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtfChassisNo = new javax.swing.JTextField();
        jtfTruckNo = new javax.swing.JTextField();
        jtfCapacity = new javax.swing.JTextField();
        jtfWeight = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Add New Truck Details");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Enter Truck No:");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Enter Weight:");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Enter Chassis No:");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Enter Capacity:");

        jtfChassisNo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jtfChassisNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfChassisNoKeyTyped(evt);
            }
        });

        jtfTruckNo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jtfTruckNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfTruckNoKeyTyped(evt);
            }
        });

        jtfCapacity.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jtfWeight.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        btnAdd.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnAdd.setText("Add Truck Details");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminui/truckcapacity.png"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminui/numbers.png"))); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminui/itemweight.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jtfChassisNo, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jtfTruckNo, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jtfCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jtfWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfTruckNo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfChassisNo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtfWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        ProSound ps = new ProSound();
        String message = "";
        boolean allvalid = true;
        String truckno = jtfTruckNo.getText().trim();
        String chassisno = jtfChassisNo.getText().trim();
        String capacity = jtfCapacity.getText().trim();
        String weight = jtfWeight.getText().trim();
        if (Validations.isEmpty(truckno)) {
            allvalid = false;
            message += "Please enter some value in Truck No box\n\n";
        }
        if (Validations.isEmpty(chassisno)) {
            allvalid = false;
            message += "Please enter some value in Chassis No box\n\n";
        }
        if (Validations.isEmpty(capacity)) {
            allvalid = false;
            message += "Please enter some value in Capacity box\n\n";
        } else if (!Validations.isFloat(capacity)) {
            allvalid = false;
            message += "Please enter decimal value in Capacity box\n\n";
        }
        if (Validations.isEmpty(weight)) {
            allvalid = false;
            message += "Please enter some value in Weight box\n\n";
        } else if (!Validations.isFloat(weight)) {
            allvalid = false;
            message += "Please enter decimal value in Weight box\n\n";
        }
        if (allvalid) {
            TruckInfo record = new TruckInfo();
            record.setTruckno(truckno);
            record.setChassisno(chassisno);
            record.setCapacity(Float.parseFloat(capacity));
            record.setWeight(Float.parseFloat(weight));
            TruckInfoDAO action = new TruckInfoDAO();
            if (btnAdd.getText().contains("Add")) {
                if (action.insertRecord(record)) {
                    ps.button();
                    message = "Truck Details are entered successfully";
                } else {
                    ps.computererror();
                    if (action.getErrormessage().contains("Duplicate entry")) {
                        message = "Truck No is a primary key and this truck no already exists.\nPlease enter some other unique value in Truck No";
                    } else {
                        message = "Insertion Failure due to:" + action.getErrormessage();
                    }
                }
            } else if (btnAdd.getText().contains("Update")) {
                if (action.updateRecord(record)) {
                    ps.button();
                    message = "Truck Details are updated successfully";
                } else {
                    ps.computererror();
                    message = "Updation Failure due to:" + action.getErrormessage();
                }
                CommonOperations.showScreen(getDesktopPane(), new ViewTrucks());
                dispose();
            } else {
                ps.computererror();
                message = "No proper operation";
            }
        } else {
            ps.computererror();
        }
        JOptionPane.showMessageDialog(this, message);
    }//GEN-LAST:event_btnAddActionPerformed

    private void jtfTruckNoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfTruckNoKeyTyped
        if (!Character.isLetterOrDigit(evt.getKeyChar())) {
            if (!Character.isWhitespace(evt.getKeyChar())) {
                evt.consume();
            }
        }
    }//GEN-LAST:event_jtfTruckNoKeyTyped

    private void jtfChassisNoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfChassisNoKeyTyped
        if (!Character.isLetterOrDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_jtfChassisNoKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jtfCapacity;
    private javax.swing.JTextField jtfChassisNo;
    private javax.swing.JTextField jtfTruckNo;
    private javax.swing.JTextField jtfWeight;
    // End of variables declaration//GEN-END:variables
}
