/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adminui;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.dao.TourScheduleDAO;
import model.to.TourSchedule;
import reports.JasperReportGenerator;
import sound.ProSound;
import specificreports.SpecificWeeklySchedule;
import utility.CommonOperations;

/**
 *
 * @author ADITYA
 */
public class ViewWeeklySchedule extends javax.swing.JInternalFrame {

    /**
     * Creates new form ViewWeeklySchedule
     */
    public ViewWeeklySchedule() {
        initComponents();
        tableWeeklySchedule.setVisible(false);
        btnLoad.setEnabled(false);
        btnReport.setEnabled(false);
    }

    public void bindTables() {
        List<TourSchedule> schedule = new TourScheduleDAO().getAllRecord(fdpTourDate.getSelectedDate());
        String message = "";
        String[] colnames = {"TRUCK NO.", "DRIVER NAME", "TOUR DATE", "NO. OF DAYS"};
        Object[][] records = null;
        if (schedule != null && schedule.size() > 0) {
            btnReport.setEnabled(true);
            message += "Weekly schedule is as shown in the given table.";
            records = new Object[schedule.size()][colnames.length];
            int i = 0;
            for (TourSchedule ts : schedule) {
                records[i] = new Object[]{ts.getTruckno(), ts.getDrivername() + "[" + ts.getDriverid() + "]", ts.getTourdate(), ts.getNoofdays()};
                i++;
            }
        } else {
            btnReport.setEnabled(false);
            message += "There is no weekly schedule available for this week.";
            records = new Object[1][colnames.length];
            records[0] = new Object[]{"No Records", "No Records", "No Records", "No Records"};
        }
        DefaultTableModel dtm = new DefaultTableModel(records, colnames) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }

        };
        tableWeeklySchedule.getTableHeader().setReorderingAllowed(false);
        tableWeeklySchedule.setAutoCreateRowSorter(true);
        tableWeeklySchedule.setModel(dtm);
        JOptionPane.showMessageDialog(this, message);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        fdpTourDate = new adminui.FutureDatePanel1();
        jLabel9 = new javax.swing.JLabel();
        btnCheckSchedule = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableWeeklySchedule = new javax.swing.JTable();
        btnLoad = new javax.swing.JButton();
        btnReport = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("View Weekly Schedule");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("Enter Tour Date:");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminui/date.png"))); // NOI18N

        btnCheckSchedule.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnCheckSchedule.setText("Check Schedule");
        btnCheckSchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckScheduleActionPerformed(evt);
            }
        });

        tableWeeklySchedule.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableWeeklySchedule);

        btnLoad.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnLoad.setText("Load Again");
        btnLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadActionPerformed(evt);
            }
        });

        btnReport.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnReport.setText("Generate Report");
        btnReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 768, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(195, 195, 195)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fdpTourDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(btnCheckSchedule, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(22, 22, 22)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)))
                .addContainerGap(40, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(btnReport, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLoad, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fdpTourDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(btnCheckSchedule, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLoad, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReport, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCheckScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckScheduleActionPerformed
        ProSound ps = new ProSound();
        String message = "";
        try {
            if (fdpTourDate.getSelectedDate() != null) {
                tableWeeklySchedule.setVisible(true);
                btnLoad.setEnabled(true);
                ps.button();
                bindTables();
            } else {
                ps.computererror();
                tableWeeklySchedule.setVisible(false);
                btnLoad.setEnabled(false);
                btnReport.setEnabled(false);
                message += "Please choose any date";
                JOptionPane.showMessageDialog(this, message);
            }

        } catch (Exception ex) {

        }
    }//GEN-LAST:event_btnCheckScheduleActionPerformed

    private void btnLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadActionPerformed
        ProSound ps = new ProSound();
        ps.button();
        bindTables();
    }//GEN-LAST:event_btnLoadActionPerformed

    private void btnReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportActionPerformed
        ProSound ps = new ProSound();
        ps.button();
        int result = JOptionPane.showConfirmDialog(this, "Do you want to generate all records ?", "Message from system", JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.YES_OPTION) {
            String path = "E:/FreightTransportationSystem/build/classes/reports/viewweeklyschedule.jrxml";
            JasperReportGenerator jrg = new JasperReportGenerator(path);
            jrg.generateReport();
        } else {
            CommonOperations.showScreen(getDesktopPane(), new SpecificWeeklySchedule());
        }    }//GEN-LAST:event_btnReportActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheckSchedule;
    private javax.swing.JButton btnLoad;
    private javax.swing.JButton btnReport;
    private adminui.FutureDatePanel1 fdpTourDate;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableWeeklySchedule;
    // End of variables declaration//GEN-END:variables
}
